### ISSUE TITLE
something wrong when i compile this project

### ISSUE THREAD

**Issue by StarryN** [PRBonn/refusion#1]
Firstly , Thanks for your awesome work!
I met something wrong with eigen when i use catkin to build this project, and the error as below:

**/usr/local/include/eigen3/Eigen/src/Core/arch/CUDA/Half.h(96): error: identifier "x" is undefined
/usr/local/include/eigen3/Eigen/src/Core/arch/CUDA/Half.h(136): error: identifier "x" is undefined
/usr/local/include/eigen3/Eigen/src/Core/arch/CUDA/Half.h(136): error: class "Eigen::half" has no member "x"
/usr/local/include/eigen3/Eigen/src/Core/arch/CUDA/Half.h(221): error: class "Eigen::half" has no member "x"
/usr/local/include/eigen3/Eigen/src/Core/arch/CUDA/Half.h(221): error: class "Eigen::half" has no member "x"
/usr/local/include/eigen3/Eigen/src/Core/arch/CUDA/Half.h(274): error: class "__half" has no member "x"
/usr/local/include/eigen3/Eigen/src/Core/arch/CUDA/Half.h(370): error: class "Eigen::half" has no member "x"
/usr/local/include/eigen3/Eigen/src/Core/arch/CUDA/Half.h(376): error: class "Eigen::half" has no member "x"
/usr/local/include/eigen3/Eigen/src/Core/arch/CUDA/Half.h(385): error: class "Eigen::half" has no member "x"
/usr/local/include/eigen3/Eigen/src/Core/arch/CUDA/Half.h(385): error: class "Eigen::half" has no member "x"
/usr/local/include/eigen3/Eigen/src/Core/arch/CUDA/Half.h(553): error: class "Eigen::half" has no member "x"
/usr/local/include/eigen3/Eigen/src/Core/arch/CUDA/Half.h(553): error: class "Eigen::half" has no member "x"
/usr/local/include/eigen3/Eigen/src/Core/arch/CUDA/Half.h(585): error: class "Eigen::half" has no member "x"**

I have tried to change the version of eigen few times, but it did not work. Can you give me some advice?

**Comment by Eman7C7** [comment]
Hi,

Which operating system are you using? And which version of Eigen?

**Comment by StarryN** [comment]
ubuntu 16.04 , I have tried eigen 3.3.4 and eigen 3.3.0

**Comment by Eman7C7** [comment]
With 3.3.4 I'm aware that it doesn't work. On ubuntu 16.04 it should work without any problem with the version of Eigen available in the repository. Try to remove all the installations of Eigen that you have on your system and just install it from apt. If it still doesn't work, try to manually install Eigen 3.3.7 and use that (follow the section "Ubuntu 18.04" of the README).

**Comment by StarryN** [comment]
Eigen 3.3.7 works well , thank you very much!
