### ISSUE TITLE
Getting segmentation fault

### ISSUE THREAD

**Issue by arnabsinha** [PRBonn/refusion#2]
Thread 1 "refusion_exampl" received signal SIGSEGV, Segmentation fault.
0x0000000000426667 in refusion::Tracker::AddScan (this=0x7fffffffd170, rgb=..., depth=...) at /home/arnab/codes/refusion_ws/src/refusion/src/tracker/tracker.cu:313
313	      image.rgb_[i * image.sensor_.cols + j] =
(gdb) bt full
#0  0x0000000000426667 in refusion::Tracker::AddScan (this=0x7fffffffd170, rgb=..., depth=...) at /home/arnab/codes/refusion_ws/src/refusion/src/tracker/tracker.cu:313
        j = 0
        i = 0
        image = {rgb_ = 0x0, depth_ = 0x0, sensor_ = {fx = 525, fy = 525, cx = 319.5, cy = 239.5, depth_factor = 1, rows = 480, cols = 640}}
        mask = 0x0
#1  0x000000000041b6a0 in main ()
No symbol table info available.

**Comment by arnabsinha** [comment]
The actual problem is occurring at:
cudaMallocManaged(&rgb_, sizeof(uchar3) * sensor_.rows * sensor.cols) 
in rgbd_image.cu code.

Any idea, what is wrong !!!
I have checked with the values of sensor.cols and sensor_.rows, and they are fine .... When I added a cuda error checking code, I am getting the following error:

"an illegal memory access was encountered"

**Comment by Eman7C7** [comment]
I think it's because you're trying to allocate more memory than you actually have. In example.cpp try to reduce tsdf_options.num_buckets and tsdf_options.num_blocks by a factor of 10 (for example) and it should work, although you might see "holes" in the map...

**Comment by aswingururaj** [comment]
@Eman7C7 How much memory do we need actually? There seems to be a lot of holes in the .obj file that is being created. I am encountering segmentation faults somewhere in the middle of data-sets as well. I am able to run the complete data-set only by setting frame_skip=2. And is there any way to run it with live sensor? Like with ROS?

**Comment by Eman7C7** [comment]
I tested it on a GTX 1080 (8GB RAM) with the default settings that you find in my code and there are no holes. Currently there is no possibility of running it live. One option is to record a rosbag and then convert it in the TUM RGB-D dataset format (you need to write a tool for it but it takes 5 minutes). Another option is to use OpenNI 2 directly. Finally, the integration with ROS is not trivial due to the large amount of CUDA code.

**Comment by arnabsinha** [comment]
> I tested it on a GTX 1080 (8GB RAM) with the default settings that you find in my code and there are no holes. Currently there is no possibility of running it live. One option is to record a rosbag and then convert it in the TUM RGB-D dataset format (you need to write a tool for it but it takes 5 minutes). Another option is to use OpenNI 2 directly. Finally, the integration with ROS is not trivial due to the large amount of CUDA code.

**Comment by arnabsinha** [comment]
> I think it's because you're trying to allocate more memory than you actually have. In example.cpp try to reduce tsdf_options.num_buckets and tsdf_options.num_blocks by a factor of 10 (for example) and it should work, although you might see "holes" in the map...

I tried this option. But I am getting the same seg fault. I also tried to decrease it to:
tsdf_options.num_buckets = 500;
tsdf_options.num_blocks = 5000;
still the problem persists.

I also tried to set 
int frame_skip = 2;
But without any improvement.
My configuration is as follows:

Device 0: "Quadro M1000M"
  CUDA Driver Version / Runtime Version          10.1 / 10.1
  CUDA Capability Major/Minor version number:    5.0
  Total amount of global memory:                 1999 MBytes (2096168960 bytes)
  ( 4) Multiprocessors, (128) CUDA Cores/MP:     512 CUDA Cores
  GPU Max Clock rate:                            1072 MHz (1.07 GHz)
  Memory Clock rate:                             2505 Mhz
  Memory Bus Width:                              128-bit
  L2 Cache Size:                                 2097152 bytes

**Comment by aswingururaj** [comment]
Hii, @arnabsinha I don't think you will be able to run it using 2GB RAM. I was also trying to do the same using GTX 750 Ti. I took the smallest data-set from their website and set the frame_skip = 2 to run the full data-set and create a mesh. Now I changed to GTX 1080 Ti. Now it runs properly.
